/**
 * filter_calendar_for_import.ts
 *
 * Reads scripts/output/calendar_report.json (generated by deep_calendar_analysis.ts)
 * and classifies every event into one of 5 buckets:
 *
 *   A_import         → High-confidence real appointments → safe to import as recalls
 *   B_review         → Likely real but ambiguous → admin should review
 *   C_exclude        → Not a patient appointment (meetings, admin, blocks)
 *   D_cancelled      → Cancelled appointment (track as no-show, don't import as completed)
 *   E_primitive_recall → Staff reminder (patient name only, no procedure)
 *
 * Run with:
 *   npx ts-node scripts/filter_calendar_for_import.ts
 *
 * Output: scripts/output/calendar_filtered.json
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Types ───────────────────────────────────────────────────────────────────

interface RawEvent {
    calendarName: string;
    date: string;
    yearMonth: string;
    year: number;
    month: number;
    dayOfWeek: number;
    hour: number;
    summary: string;
    description: string;
    organizer: string;
    attendees: string[];
    treatment: string;
    isAllDay: boolean;
    status: string;
    duration_min: number;
}

type Bucket = 'A_import' | 'B_review' | 'C_exclude' | 'D_cancelled' | 'E_primitive_recall';

interface ClassifiedEvent extends RawEvent {
    bucket: Bucket;
    score: number;
    signals: string[];
    extractedName?: string;
    extractedProcedure?: string;
    suggestedRecallType?: string;
    isNewFormat?: boolean;  // "nombre apellido procedimiento ariel" style
    isOldFormat?: boolean;  // "Nombre Apellido - Procedimiento" style
}

// ─── Normalization ────────────────────────────────────────────────────────────

function normalize(str: string): string {
    return str
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9\s]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

// ─── Recall type detection ────────────────────────────────────────────────────

const RECALL_KEYWORDS: Record<string, string> = {
    'limpieza': 'limpieza',
    'profilaxis': 'limpieza',
    'botox': 'botox',
    'carilla': 'control_carillas',
    'carillas': 'control_carillas',
    'veneer': 'control_carillas',
    'faceta': 'control_carillas',
    'blanqueamiento': 'blanqueamiento',
    'ortodoncia': 'control_ortodoncia',
    'alineador': 'control_ortodoncia',
    'invisalign': 'control_ortodoncia',
    'implante': 'mantenimiento_implantes',
    'implantes': 'mantenimiento_implantes',
    'mantenimiento': 'mantenimiento_implantes',
};

function detectRecallType(text: string): string | undefined {
    const norm = normalize(text);
    for (const [kw, type] of Object.entries(RECALL_KEYWORDS)) {
        if (norm.split(/\s+/).includes(normalize(kw)) || norm.includes(` ${normalize(kw)} `)) {
            return type;
        }
    }
    return undefined;
}

// ─── Name extraction ──────────────────────────────────────────────────────────

function extractNameFromOldFormat(summary: string): string {
    // "Nombre Apellido - Procedimiento CONFIRMO" → "Nombre Apellido"
    return summary
        .replace(/\s*[-–]\s*.*/g, '')
        .replace(/\(.*?\)/g, '')
        .replace(/\b(CANCELO|CANCELADO|CONFIRMO|CONF\.|NO VIENE|CANCELA)\b/gi, '')
        .trim();
}

function extractProcedureFromOldFormat(summary: string): string | undefined {
    const dashIdx = summary.search(/\s*[-–]\s*/);
    if (dashIdx < 0) return undefined;
    return summary
        .slice(dashIdx)
        .replace(/^[\s\-–]+/, '')
        .replace(/\b(CONFIRMO|CONF\.|CANCELO|CANCELADO)\b/gi, '')
        .trim();
}

function extractNameFromNewFormat(summary: string): string {
    // "nombre apellido procedimiento ariel" → strip "ariel" at end, then take first 2 words
    const cleaned = summary
        .replace(/\bariel\s*$/i, '')
        .replace(/\babonar\b/gi, '')
        .replace(/\b(cancelado|cancelo|cancela|primera vez|1ra vez|primer turno|1er turno)\b/gi, '')
        .trim();

    const words = cleaned.split(/\s+/).filter(w => w.length > 1);
    // Take first 2-3 words as name (skip known procedure words)
    const procedureWords = Object.keys(RECALL_KEYWORDS).map(normalize);
    const nameWords = [];
    for (const w of words) {
        if (procedureWords.includes(normalize(w))) break;
        nameWords.push(w);
        if (nameWords.length >= 3) break;
    }
    return nameWords.join(' ');
}

// ─── Pattern checks ───────────────────────────────────────────────────────────

/** Looks like a proper name: ≥2 capitalized words (old format) or ≥2 words of len≥3 (new format) */
function looksLikePatientName(summary: string): boolean {
    const cleaned = summary
        .replace(/\s*[-–]\s*.*/g, '')
        .replace(/\(.*?\)/g, '')
        .replace(/\b(CANCELO|CANCELADO|CONFIRMO|CONF\.|NO VIENE|CANCELA|ABONAR|ariel|1ra vez|primera vez)\b/gi, '')
        .trim();

    const words = cleaned.split(/\s+/).filter(w => w.length >= 2);
    if (words.length < 2) return false;

    // Old-style: capitalized
    const capitalizedWords = words.filter(w => /^[A-ZÁÉÍÓÚÑÜ]/.test(w));
    if (capitalizedWords.length >= 2) return true;

    // New-style: all lowercase but ≥2 words each with ≥3 chars
    const longWords = words.filter(w => w.length >= 3);
    return longWords.length >= 2;
}

/** Calendly consultation/meeting event (has "y AM Estética Dental" or "AM Estética Dental") */
function isCalendlyMeeting(event: RawEvent): boolean {
    const norm = normalize(event.summary);
    return norm.includes('am estetica dental') || norm.includes('estetica dental');
}

/** Description is a Zoom/Calendly invite */
function hasZoomDescription(description: string): boolean {
    const norm = normalize(description);
    return norm.includes('zoom.us') || norm.includes('zoom.com') || norm.includes('calendly.com');
}

// ─── Hard-exclude word lists ──────────────────────────────────────────────────

const HARD_EXCLUDE_WORDS_NORM = [
    'reunion',     // meetings
    'reuniones',
    'zoom',        // zoom calls
    'residuo',     // trash/waste reminders
    'vacacion',    // vacations
    'feriado',     // holidays
    'bloqueo',     // schedule blocks
    'bloquear',
    'upward',      // vendor meeting
];

const PAYMENT_REMINDER_WORDS_NORM = ['abonar', 'cobrar', 'pago pendiente'];

// ─── Main classifier ──────────────────────────────────────────────────────────

function classifyEvent(event: RawEvent): ClassifiedEvent {
    const normSummary = normalize(event.summary);
    const normFull = normalize(event.summary + ' ' + event.description);
    const signals: string[] = [];
    let score = 0;

    // ── Hard excludes ────────────────────────────────────────────────────────

    // All-day events (holiday markers, admin blocks)
    if (event.isAllDay) {
        return { ...event, bucket: 'C_exclude', score: -100, signals: ['EXCLUDE: all-day event'] };
    }

    // Very long duration (block, not a patient session)
    if (event.duration_min > 300) {
        return {
            ...event,
            bucket: 'C_exclude',
            score: -100,
            signals: [`EXCLUDE: duration ${event.duration_min} min > 300 (schedule block)`],
        };
    }

    // Calendly consultation meeting
    if (isCalendlyMeeting(event)) {
        const reason = 'EXCLUDE: Calendly consultation meeting (AM Estética Dental)';
        signals.push(reason);
        return { ...event, bucket: 'C_exclude', score: -100, signals };
    }

    // Zoom meeting in description (even if not in title)
    if (hasZoomDescription(event.description)) {
        signals.push('EXCLUDE: Zoom/Calendly description');
        return { ...event, bucket: 'C_exclude', score: -100, signals };
    }

    // Hard-exclude words in title
    for (const w of HARD_EXCLUDE_WORDS_NORM) {
        const words = normSummary.split(/\s+/);
        if (words.some(word => word.startsWith(w))) {
            signals.push(`EXCLUDE: keyword "${w}" in summary`);
            return { ...event, bucket: 'C_exclude', score: -100, signals };
        }
    }

    // Doctor/staff unavailable marker: "Ariel NO" or "ARI NO" at end
    if (/\b(ariel|ari)\s+no\s*$/i.test(event.summary)) {
        signals.push('EXCLUDE: doctor unavailable marker (Ariel NO)');
        return { ...event, bucket: 'C_exclude', score: -100, signals };
    }

    // ── Cancelled ────────────────────────────────────────────────────────────

    const cancelWords = ['cancelado', 'cancelo', 'cancela', 'no viene', 'no se presenta'];
    const cancelMatch = cancelWords.find(w => normSummary.includes(normalize(w)));
    if (cancelMatch) {
        signals.push(`CANCELLED: "${cancelMatch}" detected`);
        const name = normSummary.startsWith(normalize('cancelado'))
            ? extractNameFromNewFormat(event.summary.replace(/^cancelado\s*/i, ''))
            : extractNameFromOldFormat(event.summary);
        return {
            ...event,
            bucket: 'D_cancelled',
            score: 0,
            signals,
            extractedName: name || undefined,
        };
    }

    // ── Scoring ──────────────────────────────────────────────────────────────

    // Payment reminder prefix → strip for analysis but flag
    const hasPaymentPrefix = PAYMENT_REMINDER_WORDS_NORM.some(w => normSummary.startsWith(w));
    if (hasPaymentPrefix) {
        signals.push('NOTE: payment reminder prefix (ABONAR/COBRAR)');
        score += 5; // still real patient data
    }

    // Detect format style
    const isOldFormat = /[-–]/.test(event.summary); // has dash separator
    const isNewFormat = /\bariel\s*$/i.test(event.summary); // ends with "ariel"

    if (isOldFormat) {
        score += 30;
        signals.push('+30: old format "Nombre - Procedimiento"');
    }

    if (isNewFormat) {
        score += 20;
        signals.push('+20: new format "nombre procedimiento ariel"');
    }

    // Procedure/recall keyword
    const recallType = detectRecallType(normFull);
    if (recallType) {
        score += 20;
        signals.push(`+20: recall keyword → ${recallType}`);
    }

    // Confirmation markers
    if (/\b(confirmo|conf\.?|confirmado)\b/i.test(event.summary)) {
        score += 15;
        signals.push('+15: CONFIRMO marker');
    }

    // New patient markers
    if (/\b(primera vez|1ra vez|primer turno|1er turno)\b/i.test(event.summary)) {
        score += 15;
        signals.push('+15: nueva primera vez marker');
    }

    // Attendee email (exclude group calendar IDs which are hex strings)
    const realAttendees = (event.attendees || []).filter(
        a => a.includes('@') && !a.includes('group.calendar.google.com') && a.length < 60
    );
    if (realAttendees.length > 0) {
        score += 15;
        signals.push(`+15: ${realAttendees.length} real attendee email(s): ${realAttendees.join(', ')}`);
    }

    // Looks like "Nombre Apellido" in title
    if (looksLikePatientName(event.summary)) {
        score += 10;
        signals.push('+10: looks like patient name');
    }

    // Clinical notes in description
    if (event.description && event.description.trim().length > 20) {
        score += 10;
        signals.push('+10: has clinical description/notes');
    }

    // Normal appointment duration
    if (event.duration_min >= 30 && event.duration_min <= 240) {
        score += 10;
        signals.push(`+10: normal duration ${event.duration_min} min`);
    }

    // ── Negative scoring ─────────────────────────────────────────────────────

    // Just a phone number
    if (/^\+?[\d\s\-(). ]{7,}$/.test(event.summary.trim())) {
        score -= 30;
        signals.push('-30: looks like phone number only');
    }

    // Very short summary (likely a note/label)
    if (event.summary.trim().length < 8) {
        score -= 20;
        signals.push('-20: very short summary');
    }

    // Admin staff names without patient context
    if (/\b(clari|clarita)\b/i.test(normSummary) && !looksLikePatientName(event.summary)) {
        score -= 40;
        signals.push('-40: admin name "Clari" with no patient context');
    }

    // ── Determine bucket ─────────────────────────────────────────────────────

    const extractedName = isOldFormat
        ? extractNameFromOldFormat(event.summary)
        : extractNameFromNewFormat(event.summary);
    const extractedProcedure = isOldFormat
        ? extractProcedureFromOldFormat(event.summary)
        : undefined;

    // Primitive recall: looks like a name-only entry (staff reminder to call patient)
    const isPrimitiveName =
        looksLikePatientName(event.summary) &&
        !recallType &&
        !isOldFormat &&
        !isNewFormat &&
        score < 25;

    let bucket: Bucket;

    // "CONF/CONFIRMO + name + duration" events without a dash (score 35) are clearly real
    const isConfirmedAppointment = /\b(conf\.?|confirmo|confirmado)\b/i.test(event.summary) && looksLikePatientName(event.summary);
    // "primera vez" without email still a real appointment
    const isNewPatient = /\b(primera vez|1ra vez|primer turno)\b/i.test(event.summary) && looksLikePatientName(event.summary);

    if (score >= 40 || isConfirmedAppointment || isNewPatient) {
        bucket = 'A_import';
        if (isConfirmedAppointment && score < 40) signals.push('→A: promoted (CONF + patient name)');
        if (isNewPatient && score < 40) signals.push('→A: promoted (primera vez + patient name)');
    } else if (isPrimitiveName) {
        bucket = 'E_primitive_recall';
        signals.push('E: name-only staff reminder (no procedure, no format markers)');
    } else if (score >= 15) {
        bucket = 'B_review';
    } else {
        bucket = 'C_exclude';
    }

    return {
        ...event,
        bucket,
        score,
        signals,
        extractedName: extractedName || undefined,
        extractedProcedure: extractedProcedure || undefined,
        suggestedRecallType: recallType,
        isNewFormat: isNewFormat || undefined,
        isOldFormat: isOldFormat || undefined,
    };
}

// ─── Console helpers ──────────────────────────────────────────────────────────

function bar(label: string, count: number, total: number, width = 30): string {
    const pct = total > 0 ? count / total : 0;
    const filled = Math.round(pct * width);
    const bar = '█'.repeat(filled) + '░'.repeat(width - filled);
    return `${label.padEnd(22)} ${bar} ${count.toString().padStart(4)} (${(pct * 100).toFixed(1)}%)`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
    const outputDir = path.resolve(process.cwd(), 'scripts/output');
    const reportPath = path.join(outputDir, 'calendar_report.json');
    const outputPath = path.join(outputDir, 'calendar_filtered.json');

    if (!fs.existsSync(reportPath)) {
        console.error('❌ calendar_report.json not found. Run deep_calendar_analysis.ts first.');
        process.exit(1);
    }

    console.log('📖 Reading calendar report...');
    const report = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));
    const rawEvents: RawEvent[] = report.rawEvents;

    console.log(`📊 Classifying ${rawEvents.length} events...\n`);

    const classified = rawEvents.map(classifyEvent);

    // Group by bucket
    const A = classified.filter(e => e.bucket === 'A_import');
    const B = classified.filter(e => e.bucket === 'B_review');
    const C = classified.filter(e => e.bucket === 'C_exclude');
    const D = classified.filter(e => e.bucket === 'D_cancelled');
    const E = classified.filter(e => e.bucket === 'E_primitive_recall');
    const total = classified.length;

    // ── Summary ──────────────────────────────────────────────────────────────

    console.log('═══════════════════════════════════════════════════════════════');
    console.log('              CALENDAR FILTER RESULTS');
    console.log('═══════════════════════════════════════════════════════════════');
    console.log(bar('A — Import (recalls)', A.length, total));
    console.log(bar('B — Review needed', B.length, total));
    console.log(bar('C — Exclude', C.length, total));
    console.log(bar('D — Cancelled', D.length, total));
    console.log(bar('E — Primitive recall', E.length, total));
    console.log('───────────────────────────────────────────────────────────────');
    console.log(`Total: ${total} events`);

    // ── Recall type breakdown for Bucket A ───────────────────────────────────
    console.log('\n📊 Recall types in Bucket A (import):');
    const typeCount: Record<string, number> = {};
    A.forEach(e => {
        const t = e.suggestedRecallType || '(sin tipo — general)';
        typeCount[t] = (typeCount[t] || 0) + 1;
    });
    Object.entries(typeCount)
        .sort((a, b) => b[1] - a[1])
        .forEach(([t, n]) => console.log(`  ${t.padEnd(30)} ${n}`));

    // ── Sample events from each bucket ───────────────────────────────────────
    const showSample = (label: string, events: ClassifiedEvent[], n = 12) => {
        console.log(`\n${label} — ${events.length} events (sample of ${Math.min(n, events.length)}):`);
        events.slice(0, n).forEach(e => {
            const type = e.suggestedRecallType ? ` [${e.suggestedRecallType}]` : '';
            console.log(`  [${String(e.score).padStart(3)}]${type} ${e.summary}`);
        });
    };

    showSample('📗 BUCKET A — Safe to import', A.sort((a, b) => b.score - a.score));
    showSample('📙 BUCKET B — Review needed', B.sort((a, b) => b.score - a.score));
    showSample('📕 BUCKET C — Excluded', C);
    showSample('🔴 BUCKET D — Cancelled', D);
    showSample('🟡 BUCKET E — Primitive recalls (staff reminders)', E);

    // ── Show score distribution ──────────────────────────────────────────────
    console.log('\n📈 Score distribution:');
    const brackets = [
        { label: 'Score ≥ 80 (A)', events: A.filter(e => e.score >= 80) },
        { label: 'Score 60-79 (A)', events: A.filter(e => e.score >= 60 && e.score < 80) },
        { label: 'Score 40-59 (A)', events: A.filter(e => e.score >= 40 && e.score < 60) },
        { label: 'Score 15-39 (B)', events: B },
        { label: 'Score < 15 (E/C)', events: [...E, ...C.filter(e => e.score >= 0)] },
    ];
    brackets.forEach(b => {
        if (b.events.length > 0) console.log(`  ${b.label.padEnd(22)} ${b.events.length}`);
    });

    // ── Export ───────────────────────────────────────────────────────────────
    const output = {
        generatedAt: new Date().toISOString(),
        sourceFile: 'calendar_report.json',
        summary: {
            total,
            A_import: A.length,
            B_review: B.length,
            C_exclude: C.length,
            D_cancelled: D.length,
            E_primitive_recall: E.length,
        },
        recallTypeBreakdown: typeCount,
        buckets: {
            A_import: A,
            B_review: B,
            C_exclude: C,
            D_cancelled: D,
            E_primitive_recall: E,
        },
    };

    fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));
    console.log(`\n✅ Filtered report saved to: ${outputPath}`);
    console.log('\n💡 Next step: review Bucket B events, then run the import step for Bucket A.');
}

main().catch(err => {
    console.error('Error:', err);
    process.exit(1);
});
