/**
 * import_calendar_recalls.ts
 *
 * Reads scripts/output/calendar_filtered.json (generated by filter_calendar_for_import.ts)
 * and imports Bucket A events as recall rules in Supabase.
 *
 * For each event it:
 *  1. Tries to fuzzy-match the extractedName against pacientes in the DB
 *  2. Creates a recall_rule with last_completed_at = event.date
 *  3. Skips if a duplicate recall already exists for that patient+type+date
 *
 * Flags:
 *   --dry-run    Only show matches without writing to DB (default: dry-run)
 *   --import     Actually write to Supabase
 *   --bucket=A   Which bucket to process (default: A)
 *   --bucket=E   Process primitive recalls bucket too (name-only entries)
 *
 * Run with:
 *   npx ts-node --transpile-only scripts/import_calendar_recalls.ts --dry-run
 *   npx ts-node --transpile-only scripts/import_calendar_recalls.ts --import
 */

import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

// ── Env loading ───────────────────────────────────────────────────────────────

function loadEnv(): Record<string, string> {
    const envPath = path.resolve(process.cwd(), '.env.local');
    const env: Record<string, string> = {};
    if (!fs.existsSync(envPath)) return env;
    fs.readFileSync(envPath, 'utf-8').split('\n').forEach(line => {
        const match = line.match(/^([^#=][^=]*)=(.*)$/);
        if (match) {
            const key = match[1].trim();
            env[key] = match[2].trim().replace(/^['"]|['"]$/g, '');
        }
    });
    return env;
}

const env = loadEnv();
const SUPABASE_URL = env.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY = env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_KEY) {
    console.error('❌ Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
    process.exit(1);
}

const supabase = createClient(SUPABASE_URL!, SERVICE_KEY!, {
    auth: { autoRefreshToken: false, persistSession: false },
});

// ── Fuzzy name matching ───────────────────────────────────────────────────────

function normalize(str: string): string {
    return str
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9\s]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

interface Patient {
    id_paciente: string;
    nombre: string;
    apellido: string;
    email: string | null;
    normFull: string;
    normNombre: string;
    normApellido: string;
}

/**
 * Find the best patient match for an extracted name string.
 * Strategy:
 *  - Split name into parts (>=3 chars each)
 *  - Require BOTH nombre AND apellido parts to appear in the event name
 *  - If multiple matches, pick the one where the match is tightest (shortest full name)
 */
function findPatientMatch(
    extractedName: string,
    patients: Patient[]
): { patient: Patient; confidence: 'high' | 'medium' } | null {
    if (!extractedName || extractedName.trim().length < 3) return null;

    const normName = normalize(extractedName);
    const nameParts = normName.split(/\s+/).filter(p => p.length >= 3);
    if (nameParts.length < 1) return null;

    const matches: Array<{ patient: Patient; score: number }> = [];

    for (const p of patients) {
        const nParts = p.normNombre.split(/\s+/).filter(x => x.length >= 3);
        const aParts = p.normApellido.split(/\s+/).filter(x => x.length >= 3);

        if (nParts.length === 0 || aParts.length === 0) continue;

        const nomeIn = nParts.some(part => normName.includes(part));
        const apellIn = aParts.some(part => normName.includes(part));

        if (nomeIn && apellIn) {
            // Score: how many parts matched / total name length (tighter = better)
            const matchCount = nParts.filter(p => normName.includes(p)).length
                + aParts.filter(p => normName.includes(p)).length;
            matches.push({ patient: p, score: matchCount });
        }
    }

    if (matches.length === 0) return null;

    // Sort by score desc, then by total name length asc (shorter = more specific match)
    matches.sort((a, b) => {
        if (b.score !== a.score) return b.score - a.score;
        const aLen = (a.patient.normFull).length;
        const bLen = (b.patient.normFull).length;
        return aLen - bLen;
    });

    const best = matches[0];
    return {
        patient: best.patient,
        confidence: matches.length === 1 ? 'high' : 'medium',
    };
}

// ── Recall type mapping ───────────────────────────────────────────────────────

const RECALL_INTERVALS: Record<string, number> = {
    limpieza: 6,
    botox: 4,
    control_carillas: 12,
    blanqueamiento: 6,
    control_ortodoncia: 6,
    mantenimiento_implantes: 12,
    otro: 6,
};

// ── Import logic ──────────────────────────────────────────────────────────────

interface FilteredEvent {
    date: string;
    summary: string;
    extractedName?: string;
    extractedProcedure?: string;
    suggestedRecallType?: string;
    score: number;
    signals: string[];
    duration_min: number;
}

interface ImportResult {
    event: FilteredEvent;
    matched: boolean;
    patient?: { id: string; name: string; confidence: string };
    recall_type: string;
    last_completed_at: string;
    imported: boolean;
    skipped_reason?: string;
}

async function importRecalls(
    events: FilteredEvent[],
    patients: Patient[],
    dryRun: boolean
): Promise<{ results: ImportResult[]; stats: Record<string, number> }> {
    const today = new Date().toISOString().split('T')[0];
    const results: ImportResult[] = [];
    const stats = {
        matched: 0, unmatched: 0, imported: 0,
        skipped_duplicate: 0, skipped_future: 0, error: 0,
    };

    for (const event of events) {
        const last_completed_at = event.date.split('T')[0];
        const recall_type = event.suggestedRecallType || 'otro';

        // Skip future appointments (they haven't happened yet)
        if (last_completed_at >= today) {
            stats.skipped_future++;
            results.push({
                event,
                matched: false,
                recall_type,
                last_completed_at,
                imported: false,
                skipped_reason: `Future date (${last_completed_at}) — not yet completed`,
            });
            continue;
        }

        // Extract best name candidate:
        // 1. Try extractedName from filter script
        // 2. If it looks generic ("Consultas", "Control"), check for a parenthetical name in summary
        //    e.g. "Consultas - Primera vez - Dr. Ariel Merino   (Juan Ignacio Roumec)"
        let nameCandidates: string[] = [];
        if (event.extractedName && event.extractedName.trim().length > 3) {
            nameCandidates.push(event.extractedName);
        }
        // Also try any name in parentheses in the full summary
        const parenMatch = event.summary.match(/\(([^)]{4,})\)/);
        if (parenMatch) {
            const parenName = parenMatch[1].trim();
            // Only use if it looks like a name (not a date/note/number)
            if (/^[A-ZÁÉÍÓÚÑÜ][a-záéíóúñü]/.test(parenName) || /^[A-Z]/.test(parenName)) {
                nameCandidates.push(parenName);
            }
        }

        // Try to match patient (try each candidate, take best)
        let match = null;
        for (const candidate of nameCandidates) {
            const m = findPatientMatch(candidate, patients);
            if (m) { match = m; break; }
        }

        if (!match) {
            stats.unmatched++;
            results.push({
                event,
                matched: false,
                recall_type,
                last_completed_at,
                imported: false,
                skipped_reason: 'No patient match found',
            });
            continue;
        }

        stats.matched++;

        const patientInfo = {
            id: match.patient.id_paciente,
            name: `${match.patient.nombre} ${match.patient.apellido}`,
            confidence: match.confidence,
        };

        if (dryRun) {
            results.push({ event, matched: true, patient: patientInfo, recall_type, last_completed_at, imported: false, skipped_reason: 'dry-run' });
            continue;
        }

        // Check if a recall already exists for this patient+type (unique constraint)
        const { data: existing } = await supabase
            .from('recall_rules')
            .select('id, last_completed_at')
            .eq('patient_id', match.patient.id_paciente)
            .eq('recall_type', recall_type)
            .maybeSingle();

        const intervalMonths = RECALL_INTERVALS[recall_type] ?? 6;
        const nextDue = new Date(last_completed_at);
        nextDue.setMonth(nextDue.getMonth() + intervalMonths);
        const next_due_date = nextDue.toISOString().split('T')[0];

        if (existing) {
            // Only update if our calendar event is MORE RECENT than what's stored
            if (last_completed_at > (existing.last_completed_at ?? '')) {
                const { error } = await supabase
                    .from('recall_rules')
                    .update({
                        last_completed_at,
                        next_due_date,
                        notes: `Actualizado desde Google Calendar. Evento: "${event.summary}" (${last_completed_at})`,
                    })
                    .eq('id', existing.id);

                if (error) {
                    stats.error++;
                    results.push({ event, matched: true, patient: patientInfo, recall_type, last_completed_at, imported: false, skipped_reason: `DB update error: ${error.message}` });
                } else {
                    stats.imported++;
                    results.push({ event, matched: true, patient: patientInfo, recall_type, last_completed_at, imported: true });
                }
            } else {
                // We already have a more recent date stored — skip
                stats.skipped_duplicate++;
                results.push({ event, matched: true, patient: patientInfo, recall_type, last_completed_at, imported: false, skipped_reason: `Recall exists with same/newer date (${existing.last_completed_at})` });
            }
            continue;
        }

        // No existing recall → INSERT
        const { error } = await supabase.from('recall_rules').insert({
            patient_id: match.patient.id_paciente,
            recall_type,
            interval_months: intervalMonths,
            window_days: 14,
            state: 'pending_contact',
            priority: 0,
            last_completed_at,
            next_due_date,
            notes: `Importado desde Google Calendar. Evento: "${event.summary}" (${last_completed_at})`,
            is_active: true,
        });

        if (error) {
            stats.error++;
            results.push({ event, matched: true, patient: patientInfo, recall_type, last_completed_at, imported: false, skipped_reason: `DB error: ${error.message}` });
        } else {
            stats.imported++;
            results.push({ event, matched: true, patient: patientInfo, recall_type, last_completed_at, imported: true });
        }
    }

    return { results, stats };
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
    const args = process.argv.slice(2);
    const dryRun = !args.includes('--import');
    const includeE = args.includes('--bucket=E');

    const outputDir = path.resolve(process.cwd(), 'scripts/output');
    const filteredPath = path.join(outputDir, 'calendar_filtered.json');
    const importReportPath = path.join(outputDir, 'calendar_import_report.json');

    if (!fs.existsSync(filteredPath)) {
        console.error('❌ calendar_filtered.json not found. Run filter_calendar_for_import.ts first.');
        process.exit(1);
    }

    console.log(`\n🔵 Mode: ${dryRun ? 'DRY RUN (no writes)' : 'IMPORT (will write to Supabase)'}`);
    if (dryRun) console.log('   Tip: pass --import flag to actually write records.\n');

    // Load filtered events
    const filtered = JSON.parse(fs.readFileSync(filteredPath, 'utf-8'));
    const eventsA: FilteredEvent[] = filtered.buckets.A_import ?? [];
    const eventsE: FilteredEvent[] = filtered.buckets.E_primitive_recall ?? [];

    // Sort DESC so the most recent appointment for each patient is processed first
    const allEvents = includeE ? [...eventsA, ...eventsE] : eventsA;
    const events = [...allEvents].sort((a, b) => b.date.localeCompare(a.date));
    console.log(`📂 Loaded ${eventsA.length} Bucket-A events${includeE ? ` + ${eventsE.length} Bucket-E events` : ''} → ${events.length} total to process (sorted by date DESC)`);

    // Load patients from Supabase
    console.log('🔌 Loading patients from Supabase...');
    const { data: patientsData, error: pErr } = await supabase
        .from('pacientes')
        .select('id_paciente, nombre, apellido, email')
        .eq('is_deleted', false);

    if (pErr) {
        console.error('❌ Failed to load patients:', pErr.message);
        process.exit(1);
    }

    const patients: Patient[] = (patientsData || []).map(p => ({
        ...p,
        normFull: normalize(`${p.nombre} ${p.apellido}`),
        normNombre: normalize(p.nombre || ''),
        normApellido: normalize(p.apellido || ''),
    }));
    console.log(`✅ Loaded ${patients.length} patients\n`);

    // Run import
    const { results, stats } = await importRecalls(events, patients, dryRun);

    // ── Print report ─────────────────────────────────────────────────────────

    console.log('═══════════════════════════════════════════════════════════════');
    console.log('              IMPORT RESULTS');
    console.log('═══════════════════════════════════════════════════════════════');
    const pastEvents = events.length - stats.skipped_future;
    console.log(`Events processed:    ${events.length}`);
    console.log(`Future (skipped):    ${stats.skipped_future}`);
    console.log(`Past events:         ${pastEvents}`);
    console.log(`Patient matches:     ${stats.matched} (${(pastEvents > 0 ? (stats.matched / pastEvents) * 100 : 0).toFixed(1)}% of past)`);
    console.log(`No match found:      ${stats.unmatched}`);
    if (!dryRun) {
        console.log(`Imported:            ${stats.imported}`);
        console.log(`Skipped (duplicate): ${stats.skipped_duplicate}`);
        console.log(`Errors:              ${stats.error}`);
    }
    console.log('───────────────────────────────────────────────────────────────');

    // ── Show matched events ──────────────────────────────────────────────────
    const matched = results.filter(r => r.matched);
    const unmatched = results.filter(r => !r.matched);

    console.log(`\n✅ MATCHED (${matched.length}) — sample:`);
    matched.slice(0, 20).forEach(r => {
        const typeStr = r.recall_type !== 'otro' ? ` [${r.recall_type}]` : '';
        const confStr = r.patient!.confidence === 'medium' ? ' ⚠️ med' : '';
        console.log(`  ${r.last_completed_at}${typeStr}${confStr}  "${r.event.extractedName}" → ${r.patient!.name}`);
    });

    if (unmatched.length > 0) {
        console.log(`\n❓ UNMATCHED (${unmatched.length}) — no patient found for:`);
        unmatched.slice(0, 30).forEach(r => {
            console.log(`  ${r.last_completed_at}  "${r.event.extractedName || '(no name)'}" | ${r.event.summary}`);
        });
        console.log('\n💡 Tip: unmatched patients can be added manually via /pacientes/nuevo');
    }

    // Recall type breakdown
    console.log('\n📊 Recall type breakdown (matched events):');
    const typeMap: Record<string, number> = {};
    matched.forEach(r => { typeMap[r.recall_type] = (typeMap[r.recall_type] || 0) + 1; });
    Object.entries(typeMap).sort((a, b) => b[1] - a[1]).forEach(([t, n]) => {
        console.log(`  ${t.padEnd(30)} ${n}`);
    });

    // ── Save report ──────────────────────────────────────────────────────────
    const report = {
        generatedAt: new Date().toISOString(),
        mode: dryRun ? 'dry_run' : 'import',
        stats,
        matched: matched.map(r => ({
            date: r.last_completed_at,
            recall_type: r.recall_type,
            extractedName: r.event.extractedName,
            patientName: r.patient!.name,
            patientId: r.patient!.id,
            confidence: r.patient!.confidence,
            imported: r.imported,
            skipped_reason: r.skipped_reason,
            originalSummary: r.event.summary,
        })),
        unmatched: unmatched.map(r => ({
            date: r.last_completed_at,
            extractedName: r.event.extractedName,
            originalSummary: r.event.summary,
            score: r.event.score,
        })),
    };

    fs.writeFileSync(importReportPath, JSON.stringify(report, null, 2));
    console.log(`\n📄 Report saved to: ${importReportPath}`);

    if (dryRun) {
        console.log('\n⚡ Ready to import! Run with --import to write to Supabase.');
        console.log('   npx ts-node --transpile-only scripts/import_calendar_recalls.ts --import');
    } else {
        console.log(`\n✅ Done! ${stats.imported} recalls created, ${stats.skipped_duplicate} duplicates skipped.`);
    }
}

main().catch(err => {
    console.error('Error:', err);
    process.exit(1);
});
